version: '3'
services:
  ctf:
    build:
      context: .
    hostname: ctf
    stdin_open: true # docker run -i
    tty: true # docker run -t
    volumes:
      - ./:/home/dev/src
    ports:
      - "2022:22"
    # Uncomment if want to use openvpn
    # Following this issue: https://github.com/OpenVPN/openvpn3-linux/issues/86
    # privileged: true
